apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-app.fullname" . }}
  labels: {{- include "django-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "django-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "django-app.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/secret-db: {{ include (print .Template.BasePath "/secret-db.yaml") . | sha256sum }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
            {{- if .Values.metrics.enabled }}
            - name: GUNICORN_CMD_ARGS
              value: "--statsd-host=127.0.0.1:9125 --statsd-prefix=django"
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "django-app.fullname" . }}-db
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: settings-local
              mountPath: /app/mysite/settings_local.py
              subPath: settings_local.py
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20

        {{- if .Values.metrics.enabled }}
        - name: statsd-exporter
          image: prom/statsd-exporter:v0.26.1
          args:
            - "--log.level=info"
          ports:
            - name: metrics
              containerPort: 9102
              protocol: TCP
            - name: statsd
              containerPort: 9125
              protocol: UDP
        {{- end }}

      volumes:
        - name: settings-local
          configMap:
            name: {{ include "django-app.fullname" . }}-settings
