apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-app.fullname" . }}-db
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  RDS_DB_NAME:    {{ .Values.db.name | quote }}
  RDS_USERNAME:   {{ .Values.db.username | quote }}
  RDS_PASSWORD:   {{ .Values.db.password | quote }}
  RDS_HOSTNAME:   {{ .Values.db.host | quote }}
  RDS_PORT:       {{ .Values.db.port | toString | quote }}
