{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "django-app.fullname" . }}-metrics
  labels:
    # kube-prometheus-stack's Prometheus usually selects ServiceMonitors with this label
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "django-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: metrics
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
{{- end }}
