apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-app.fullname" . }}
  labels: {{- include "django-app.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Cluster
  selector: {{- include "django-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
